services:
  isaens-landing:
    image: ghcr.io/soporteasonaman/isaens-landing:latest
    container_name: isaens-landing
    restart: always
    networks:
      - isaens-public

networks:
  isaens-public:
    external: true
